# 工作流名称
name: Assemble Ios Debug

# 触发工作流程的事件
on:
  push:
    tags: [ v* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# 工作流环境变量
env:
  # 应用的application_id
  APP_ID: ${{secrets.APP_ID}}
  APP_NAME: Taro
  BUILD_TYPE: debug
  IOS_VERSION_NUMBER: 1.4.1
  IOS_TEAM_ID: ${{secrets.TEAM_ID}}
  IOS_PROVISIONING_PROFILE_SPECIFIER: ${{secrets.DEBUG_PROVISIONING_PROFILE_SPECIFIER}}
  IOS_CODE_SIGN_IDENTITY: iPhone Developer
  IOS_SIGNING_CERTIFICATE_P12_DATA: ${{secrets.DEBUG_SIGNING_CERTIFICATE_P12_DATA}}
  IOS_SIGNING_CERTIFICATE_PASSWORD: ${{secrets.DEBUG_SIGNING_CERTIFICATE_PASSWORD}}
  IOS_PROVISIONING_PROFILE_DATA: ${{secrets.DEBUG_PROVISIONING_PROFILE_DATA}}
  IOS_APP_STORE_CONNECT_USERNAME: ${{secrets.APP_STORE_CONNECT_USERNAME}}
  IOS_APP_STORE_CONNECT_PASSWORD: ${{secrets.APP_STORE_CONNECT_PASSWORD}}
  
jobs:
  assemble:
    runs-on: macos-11
    steps:
      - name: echo PROVISIONING_PROFILE
        run:
          echo $APP_ID $IOS_TEAM_ID $IOS_PROVISIONING_PROFILE_SPECIFIER $DEBUG_PROVISIONING_PROFILE_DATA
      - name: echo SIGNING_CERTIFICATE
        run:
          echo $IOS_APP_STORE_CONNECT_USERNAME $IOS_APP_STORE_CONNECT_PASSWORD $DEBUG_SIGNING_CERTIFICATE_PASSWORD $DEBUG_SIGNING_CERTIFICATE_P12_DATA
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Cache node_modules Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Dependencies
        run: |
          yarn
      - name: Build Taro React Native Bundle
        run: |
          yarn build:rn --platform ios
      - name: Install pods
        run: cd ios && pod update --no-repo-update
      - name: Change react-native-xcode.sh
        run: |
          cd node_modules/react-native/scripts
          echo "exit 0;">react-native-xcode.sh
      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ env.IOS_SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ env.IOS_SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh
      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ env.IOS_PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh
