# 工作流名称
name: Assemble Ios Debug

# 触发工作流程的事件
on:
  push:
    tags: [ v* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# 工作流环境变量
env:
  # 应用的application_id
  APP_ID: ${{secrets.APP_ID}}
  APP_NAME: Taro
  BUILD_TYPE: debug
  IOS_VERSION_NUMBER: 1.4.1
  IOS_TEAM_ID: ${{secrets.TEAM_ID}}
  IOS_PROVISIONING_PROFILE_SPECIFIER: ${{secrets.DEBUG_PROVISIONING_PROFILE_SPECIFIER}}
  IOS_CODE_SIGN_IDENTITY: iPhone Developer
  IOS_SIGNING_CERTIFICATE_P12_DATA: ${{secrets.DEBUG_SIGNING_CERTIFICATE_P12_DATA}}
  IOS_SIGNING_CERTIFICATE_PASSWORD: ${{secrets.DEBUG_SIGNING_CERTIFICATE_PASSWORD}}
  IOS_PROVISIONING_PROFILE_DATA: ${{secrets.DEBUG_PROVISIONING_PROFILE_DATA}}
  IOS_APP_STORE_CONNECT_USERNAME: ${{secrets.APP_STORE_CONNECT_USERNAME}}
  IOS_APP_STORE_CONNECT_PASSWORD: ${{secrets.APP_STORE_CONNECT_PASSWORD}}
  
jobs:
  assemble:
    runs-on: macos-11
    steps:
      - name: echo DEBUG_SIGNING_CERTIFICATE_PASSWORD
        run:
          echo $IOS_PROVISIONING_PROFILE_SPECIFIER $IOS_SIGNING_CERTIFICATE_PASSWORD $IOS_APP_STORE_CONNECT_USERNAME
      - name: echo DEBUG_PROVISIONING_PROFILE_DATA
        run:
          echo $IOS_PROVISIONING_PROFILE_DATA
      - name: echo SIGNING_CERTIFICATE
        run:
          echo $IOS_SIGNING_CERTIFICATE_P12_DATA

